version: "3.7"

services:
  #build the blazor app using microsoft's docker file
  web:
    build: .
    #bind the ports to the host machine
    ports:
      - "8080:80"
    # link this with mssql in order to access its exposed ports
    links:
      - mssql
    # prevent this container from starting before mssql
    depends_on:
      - mssql
    container_name: Dingo-Blazor

  importer:
    image: mcr.microsoft.com/mssql-tools:latest
    volumes:
      - ./ImportSQL:/var/opt/mssql/import
    links:
      - mssql
    depends_on:
      - mssql
    container_name: MSSQL-Script-Importer
    working_dir: /var/opt/mssql/import
    command: "sh ./AutoImport.sh"

  # set up the db that runs the app
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    # expose this port to host for debug puposes
    ports:
      - "11433:1433"
    # use mssql-server,11433(docker) / localhost,11433(other)
    expose:
      - "1433/tcp"
    # setup MSSQL
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "DingoChat5%"
      MSSQL_PID: "Developer"
    # visual name for docker-gui
    container_name: Dingo-MSSQL
    # for some reason mssql-tools refused to connect to a linked container unless this had a hostname??
    hostname: mssql-server

  